service: thumbnail-generator

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-1

functions:
  app:
    handler: dist/index.handler
    events:
      - http: ANY /
      - http: "ANY {proxy+}"
